server:
  context-path: "/management_app"

spring:
  mvc:
    view:
      prefix: "/WEB-INF/view/"
      suffix: ".jsp"
  kafka:
    bootstrap-servers: "127.0.0.1:29092"
    consumer:
      group-id: "task"

logging:
  level:
    org:
      apache:
        kafka: "WARN"

kafka:
  topic:
    producer:
      name: "request_product_topic"
    consumer:
      name: "response_product_topic"
      poll-interval: 3000

sonar:
  projectKey: "management-app"
  projectName: "SKT Management App"
  host:
    url: "http://localhost:9000"